services:
  web:
    container_name: web-backend
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
    command: sh entrypoint.sh
    
  redis:
    image: redis
    container_name: redis-server
